# Generated by Django 6.0.6 on 2026-06-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('investment', 'Investment Account'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('business', 'Business Account')], max_length=20)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for income, negative for expenses', max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import'), ('bank_import', 'Bank Import'), ('api_import', 'API Import')], default='manual', max_length=20)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
