# Generated by Django 6.0.6 on 2026-08-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Internal symbol (e.g. EURUSD, XAUUSD)', max_length=20, unique=True)),
                ('provider_symbol', models.CharField(help_text='Symbol used by the data provider (e.g. EURUSD=X, GC=F)', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_type', models.CharField(choices=[('FOREX', 'Forex'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1H', '1 Hour'), ('4H', '4 Hour'), ('1D', 'Daily')], max_length=2)),
                ('datetime', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='markets.market')),
            ],
            options={
                'ordering': ['market', 'timeframe', '-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='markets.candle')),
            ],
            options={
                'unique_together': {('candle', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['market', 'timeframe'], name='markets_can_market__1fdf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['datetime'], name='markets_can_datetim_a94c68_idx'),
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('market', 'timeframe', 'datetime'), name='unique_market_candle'),
        ),
    ]
