# Generated by Django 6.0.6 on 2026-08-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candle",
            new_name="MarketPrice",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="candle",
            new_name="market_price",
        ),
        migrations.AlterField(
            model_name="marketprice",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_prices",
                to="markets.market",
            ),
        ),
    ]
