# Generated by Django 6.0.6 on 2026-08-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_rename_candle_to_marketprice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketprice',
            name='unique_market_candle',
        ),
        migrations.RenameIndex(
            model_name='marketprice',
            new_name='markets_mar_market__6b4b6f_idx',
            old_name='markets_can_market__1fdf0b_idx',
        ),
        migrations.RenameIndex(
            model_name='marketprice',
            new_name='markets_mar_datetim_2d2507_idx',
            old_name='markets_can_datetim_a94c68_idx',
        ),
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.UniqueConstraint(fields=('market', 'timeframe', 'datetime'), name='unique_market_price'),
        ),
    ]
