# Generated by Django 6.0.6 on 2026-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_remove_marketprice_unique_market_candle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
